services:
  api:
    container_name: api_products
    image: api_express_products
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_USER=igor
      - DB_PASSWORD=0185
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB=products_management
    depends_on:
      - db
  db:
    container_name: db_bug
    image: postgres:12
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=igor
      - POSTGRES_PASSWORD=0185
      - POSTGRES_DB=products_management
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
